---
title: Josh Hamilton Design
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:title/"
    role:
    - 
    examples:
    - image:
        image:
        is-half:
        is-full:
      caption: 
      background-color: 
      is-featured:
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: work
  values:
    layout: work
    permalink: "/work/:title/"
    year: 
    link: 
    role:
    - 
    examples:
    - image:
        image:
        is-half:
        is-full:
      caption: 
      background-color: 
      is-featured:
permalink: pretty
sass:
  sass_dir: assets/styles/
  style: compressed
site-logo: "/uploads/logo.png"
about-headline: Josh Hamilton is a print and digital product designer in the Charlotte area.
intro-text: Currently I'm the Senior Designer for Thorlos, a foot protection sock brand. Working alongside maketing, sales, engineering and product development.
