---
title: Portfolio of Josh Hamilton
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: Work
    output: true
    permalink: "/work/:title/"
    role:
    - 
    examples:
    - image:
        image: 
        is-half: 
        is-full: 
      caption: 
      background-color: 
      is-featured: 
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: work
  values:
    layout: work
    permalink: "/work/:title/"
    year: 
    link: 
    role:
    - 
    examples:
    - image:
        image: 
        is-half: 
        is-full: 
      caption: 
      background-color: 
      is-featured: 
permalink: pretty
sass:
  sass_dir: assets/styles/
  style: compressed
site-logo: "/uploads/logo.png"
about-headline: 'I''m a designer and web builder in the Charlotte area. '
intro-text: 'I''m currently the Senior Designer for Thorlos. Browse some of my work,
  Download my [resume](https://www.dropbox.com/s/yq7k7djo0glztrq/JoshHamilton-resume.pdf?dl=0)
  for past work experience. Or just reach out and say&nbsp;hello. '
